# Generated by Django 3.0.4 on 2020-08-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_lesson_task_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Бесплатно'),
        ),
    ]
