# Generated by Django 3.0.4 on 2020-08-27 21:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20200828_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Course.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='lessontasks',
            name='ans_a',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ А'),
        ),
        migrations.AlterField(
            model_name='lessontasks',
            name='ans_b',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ B'),
        ),
        migrations.AlterField(
            model_name='lessontasks',
            name='ans_c',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ С'),
        ),
        migrations.AlterField(
            model_name='lessontasks',
            name='ans_d',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ D'),
        ),
        migrations.AlterField(
            model_name='lessontasks',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Course.Course', verbose_name='Курс'),
        ),
    ]
