# Generated by Django 3.0.4 on 2020-09-01 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_lesson_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_kz',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_a_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ А'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_a_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ А'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_a_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ А'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_b_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ B'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_b_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ B'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_b_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ B'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_c_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ С'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_c_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ С'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_c_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ С'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_d_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ D'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_d_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ D'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_d_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ D'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='description_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='name_kz',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
    ]
