# Generated by Django 3.0.4 on 2020-09-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_auto_20200901_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description_kz',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name_kz',
        ),
        migrations.RemoveField(
            model_name='lessontasks',
            name='ans_a_kz',
        ),
        migrations.RemoveField(
            model_name='lessontasks',
            name='ans_b_kz',
        ),
        migrations.RemoveField(
            model_name='lessontasks',
            name='ans_c_kz',
        ),
        migrations.RemoveField(
            model_name='lessontasks',
            name='ans_d_kz',
        ),
        migrations.RemoveField(
            model_name='lessontasks',
            name='description_kz',
        ),
        migrations.RemoveField(
            model_name='lessontasks',
            name='name_kz',
        ),
    ]
