# Generated by Django 3.0.4 on 2020-09-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_moduleprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleprice',
            options={'verbose_name': 'Цены за Модуль', 'verbose_name_plural': 'Цены за Модуль'},
        ),
    ]
