# Generated by Django 3.0.4 on 2020-09-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0016_auto_20200910_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='vimeo_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
