# Generated by Django 3.0.4 on 2020-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0017_auto_20200911_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
