# Generated by Django 3.0.4 on 2020-09-13 20:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0018_moduleuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_kz',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_a_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ А'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_b_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ B'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_c_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ С'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='ans_d_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ D'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='description_kz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lessontasks',
            name='name_kz',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
    ]
