# Generated by Django 3.0.4 on 2020-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0020_auto_20200914_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Имя'),
        ),
    ]
