# Generated by Django 3.0.4 on 2020-05-06 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lesson', '0015_auto_20200417_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.Analytics')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lesson.Category')),
            ],
            options={
                'verbose_name': 'Аналитика категории',
                'verbose_name_plural': 'Аналитика категории',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата последнего посещения')),
                ('analytics_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.AnalyticsCategory')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lesson.Lesson', verbose_name='урок')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аналитика уроков',
                'verbose_name_plural': 'Аналитика уроков',
            },
        ),
    ]
