# Generated by Django 3.0.4 on 2020-05-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticscategory',
            old_name='category',
            new_name='sub_category',
        ),
    ]
