# Generated by Django 3.0.4 on 2020-05-12 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0015_auto_20200417_1607'),
        ('Analytics', '0002_auto_20200512_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticscategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lesson.SubCategory'),
        ),
        migrations.AlterField(
            model_name='analyticslesson',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего посещения'),
        ),
    ]
