# Generated by Django 3.0.4 on 2020-08-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_groups', to='Test.TestCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestGroupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('duration', models.IntegerField()),
                ('pass_min', models.IntegerField()),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_group_categories', to='Test.TestGroup', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Категории тестов',
                'verbose_name_plural': 'Категории тестов',
            },
        ),
        migrations.CreateModel(
            name='TestTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2, verbose_name='Правильный ответ')),
                ('ans_a', models.TextField(verbose_name='Ответ А')),
                ('ans_b', models.TextField(verbose_name='Ответ B')),
                ('ans_c', models.TextField(verbose_name='Ответ С')),
                ('ans_d', models.TextField(verbose_name='Ответ D')),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Test.TestGroupCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопросы тестов',
                'verbose_name_plural': 'Вопросы тестов',
            },
        ),
    ]
