# Generated by Django 3.0.4 on 2020-08-28 02:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0002_auto_20200827_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtasks',
            name='ans_a',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ А'),
        ),
        migrations.AlterField(
            model_name='testtasks',
            name='ans_b',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ B'),
        ),
        migrations.AlterField(
            model_name='testtasks',
            name='ans_c',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ С'),
        ),
        migrations.AlterField(
            model_name='testtasks',
            name='ans_d',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ D'),
        ),
        migrations.AlterField(
            model_name='testtasks',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='TestGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.TestGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
