# Generated by Django 3.0.4 on 2020-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20200828_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
