# Generated by Django 3.0.4 on 2020-09-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_testgroup_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
