# Generated by Django 3.0.4 on 2020-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_testgroup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroupuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
