# Generated by Django 3.0.4 on 2020-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='grade',
            field=models.IntegerField(default=6, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='parent_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя Родителей'),
        ),
    ]
