# Generated by Django 3.0.4 on 2020-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20200901_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Казахский'), (2, 'Русский'), (3, 'Английский')], default=2, verbose_name='Язык'),
        ),
    ]
